import { Injectable } from '@angular/core';
import { CompanyDetails } from '../../app.component.models';

@Injectable({
  providedIn: 'root'
})
export class ActivitiesService {
  companiesDetails: Array<CompanyDetails> = [
    {
      companyId: 1,
      title: "The Activities of the Investment Company",
      titleAr: "أنشطة الشركة الاستثماريّة",
      caption: "Empowering growth through strategic investment",
      captionAr: "تمكين النمو من خلال الاستثمار الاستراتيجي",
      activities: [
        { id: 1, name: 'General Trading', nameAr: "تجارة عامة", image: 'assets/images/slider/img1.webp', description: "is a key activity of UAE Investment and Development Company, facilitating the import, export, and distribution of diverse products. Through strategic partnerships and market expertise, we ensure efficient trade operations that meet regional demand and support economic growth.", descriptionAr: "تُعدّ أحد الأنشطة الرئيسية لشركة يو إيه إي للاستثمار والتنمية، حيث نمكّن من استيراد وتصدير وتوزيع منتجات متنوعة. ومن خلال شراكاتنا الاستراتيجية وخبرتنا في السوق، نضمن عمليات تجارية فعّالة تلبي الطلب الإقليمي وتدعم النمو الاقتصادي." },
        { id: 2, name: 'Investment in Commercial Enterprises & Management', nameAr: "الاستثمار في المشروعات التجارية وتأسيسها وإدارتها", image: 'assets/images/slider/img2.webp', description: "is one of the core activities of UAE Investment and Development Company, dedicated to establishing, managing, and growing high-value business ventures. We provide strategic planning, operational expertise, and investment support to maximize performance and achieve sustainable profitability.", descriptionAr: "يُعدّ أحد الأنشطة الأساسية لشركة يو إيه إي للاستثمار والتنمية، حيث نكرّس جهودنا لإنشاء وإدارة وتنمية مشروعات عالية القيمة. نقدم التخطيط الاستراتيجي والخبرة التشغيلية والدعم الاستثماري لتعظيم الأداء وتحقيق الربحية المستدامة." },
        { id: 3, name: 'Investment in Industrial Enterprises & Management', nameAr: "الاستثمار في المشروعات الصناعية وتأسيسها وإدارتها", image: 'assets/images/slider/img3.webp', description: "is a core focus of UAE Investment and Development Company, aimed at developing, managing, and enhancing industrial assets. We support modernization, innovation, and operational efficiency to boost productivity and ensure long-term sector growth.", descriptionAr: "يُعدّ محوراً أساسياً لشركة يو إيه إي للاستثمار والتنمية، ويهدف إلى تطوير وإدارة وتعزيز الأصول الصناعية. ندعم التحديث والابتكار وكفاءة العمليات لزيادة الإنتاجية وضمان نمو القطاع على المدى الطويل." },
        { id: 4, name: 'Investment in Agricultural Enterprises & Management', nameAr: "الاستثمار في المشروعات الزراعية وتأسيسها وإدارتها", image: 'assets/images/slider/img4.webp', description: "is a vital activity of UAE Investment and Development Company, focused on developing and managing agricultural assets. We promote modern farming practices, efficient operations, and innovative solutions to increase productivity and ensure sustainability.", descriptionAr: "يُعدّ نشاطاً حيوياً لشركة يو إيه إي للاستثمار والتنمية، حيث نركز على تطوير وإدارة الأصول الزراعية. ندعم أساليب الزراعة الحديثة، وكفاءة العمليات، والحلول المبتكرة لزيادة الإنتاجية وضمان الاستدامة." },
        { id: 5, name: 'Investment in Oil & Natural Gas Projects', nameAr: "الاستثمار في مشروعات النفط والغاز الطبيعي", image: 'assets/images/slider/img5.webp', description: "is a key priority for UAE Investment and Development Company, focusing on energy infrastructure and strategic partnerships. We work to promote sustainable extraction, improve processing efficiency, and drive long-term growth in the energy sector.", descriptionAr: "يُعدّ أولوية رئيسية لشركة يو إيه إي للاستثمار والتنمية، حيث نركز على البنية التحتية للطاقة والشراكات الاستراتيجية. نعمل على تعزيز الاستخراج المستدام، وتحسين كفاءة المعالجة، ودفع النمو طويل الأمد في قطاع الطاقة." },
        { id: 6, name: 'Investment in Sport Enterprises & Development', nameAr: "الاستثمار في المشروعات الرياضية وتطويرها", image: 'assets/images/slider/img6.webp', description: "is a key activity of UAE Investment and Development Company, dedicated to advancing the sports sector. We support infrastructure development, talent growth, and major events to strengthen the sector’s impact and sustainability.", descriptionAr: "يُعدّ أحد الأنشطة الرئيسية لشركة يو إيه إي للاستثمار والتنمية، حيث نكرّس جهودنا لتطوير قطاع الرياضة. ندعم تطوير البنية التحتية، وتنمية المواهب، وتنظيم الفعاليات الكبرى لتعزيز تأثير القطاع واستدامته." },
        { id: 7, name: 'Investment in Water Enterprises & Development', nameAr: "الاستثمار في مشروعات المياه وتطويرها", image: 'assets/images/slider/img7.webp', description: "is a vital focus of UAE Investment and Development Company, aimed at improving water resources and infrastructure. We promote sustainable management, innovative technologies, and efficient solutions to enhance water availability and quality.", descriptionAr: "يُعدّ محوراً حيوياً لشركة يو إيه إي للاستثمار والتنمية، ويهدف إلى تحسين موارد المياه والبنية التحتية. ندعم الإدارة المستدامة، والتقنيات المبتكرة، والحلول الفعّالة لتعزيز توافر المياه وجودتها." },
        { id: 8, name: 'Investment in Healthcare Enterprises & Development', nameAr: "الاستثمار في مشروعات الخدمات الصحية وتأسيسها وإدارتها", image: 'assets/images/slider/img8.webp', description: "is a core activity of UAE Investment and Development Company, focused on enhancing healthcare facilities and services. We support innovative solutions, quality care, and sustainable growth to strengthen the healthcare sector.", descriptionAr: "يُعدّ أحد الأنشطة الرئيسية لشركة يو إيه إي للاستثمار والتنمية، ويركز على تطوير مرافق وخدمات الرعاية الصحية. ندعم الحلول المبتكرة، وجودة الرعاية، والنمو المستدام لتعزيز القطاع الصحي." },
        { id: 9, name: 'Investment in Educational Enterprises & Management', nameAr: "الاستثمار في المشروعات التعليمية وتأسيسها وإدارتها", image: 'assets/images/slider/img9.webp', description: "is a key activity of UAE Investment and Development Company, aimed at developing and managing educational institutions. We enhance infrastructure, adopt innovative learning methods, and foster skilled future generations to strengthen the education sector.", descriptionAr: "يُعدّ أحد الأنشطة الرئيسية لشركة يو إيه إي للاستثمار والتنمية، ويهدف إلى تطوير وإدارة المؤسسات التعليمية. نقوم بتحسين البنية التحتية، واعتماد أساليب تعليم مبتكرة، وتنمية الأجيال المستقبلية الماهرة لتعزيز قطاع التعليم." },
        { id: 10, name: 'Investment in Tourist Enterprises & Management', nameAr: "الاستثمار في المشروعات السياحية وتأسيسها وإدارتها", image: 'assets/images/slider/img10.webp', description: "is a key activity of UAE Investment and Development Company, focused on developing and managing tourism projects. We enhance facilities, support sustainable initiatives, and create engaging experiences to attract visitors and drive sector growth.", descriptionAr: "يُعدّ أحد الأنشطة الرئيسية لشركة يو إيه إي للاستثمار والتنمية، ويركز على تطوير وإدارة المشاريع السياحية. نقوم بتحسين المرافق، ودعم المبادرات المستدامة، وخلق تجارب جذابة لجذب الزوار وتعزيز نمو القطاع." },
        { id: 11, name: 'Investment in Technological Enterprises & Management', nameAr: "الاستثمار في المشروعات التكنولوجيّة وتأسيسها وإدارتها", image: 'assets/images/slider/img11.webp', description: "is a strategic activity of UAE Investment and Development Company, dedicated to establishing, managing, and advancing technological ventures. We focus on fostering innovation, supporting digital transformation, and enabling sustainable tech-driven growth to strengthen competitiveness in the global market.", descriptionAr: "يُعدّ نشاطاً استراتيجياً لشركة يو إيه إي للاستثمار والتنمية، حيث نكرّس جهودنا لإنشاء وإدارة وتطوير المشروعات التكنولوجية. نركز على تعزيز الابتكار، ودعم التحول الرقمي، وتمكين النمو المستدام المعتمد على التكنولوجيا لتعزيز القدرة التنافسية في السوق العالمية." },
        { id: 12, name: 'Investment in Energy Enterprises & Management', nameAr: "الاستثمار في مشروعات الطاقة وتأسيسها وإدارتها", image: 'assets/images/slider/img12.webp', description: "is a key activity of UAE Investment and Development Company, focused on developing and managing energy projects. We promote sustainable energy solutions, optimize resource use, and foster innovation to ensure long-term efficiency and sector growth.", descriptionAr: "يُعدّ أحد الأنشطة الرئيسية لشركة يو إيه إي للاستثمار والتنمية، ويركز على تطوير وإدارة مشاريع الطاقة. ندعم حلول الطاقة المستدامة، وتحسين استخدام الموارد، وتعزيز الابتكار لضمان الكفاءة والنمو طويل الأمد للقطاع." }
      ]
    },
    {
      companyId: 2,
      title: "The Activities of the Property Company",
      titleAr: "أنشطة الشركة العقاريّة",
      caption: "Your partner in profitable property investment",
      captionAr: "شريكك في الاستثمار العقاري المربح",
      activities: [
        { id: 1, name: 'Buying & Selling of Real Estate', nameAr: 'شراء الاراضي والعقارات وبيعها', image: 'assets/images/properties/img1.webp', description: "is a core service of UAE International Property. We guide clients with expert advice, connecting them to the best property opportunities across the UAE. Our process is transparent, efficient, and designed to maximize value, ensuring smooth and successful transactions from start to finish.", descriptionAr: "يعد أحد الخدمات الأساسية لشركة يو ايه إي انترناشيونال للعقارات. نقدم لعملائنا إرشاداً متخصصاً، ونربطهم بأفضل الفرص العقارية المتاحة في جميع أنحاء الإمارات العربية المتحدة. يتميز أسلوبنا بالشفافية والكفاءة مع التركيز على تحقيق أقصى قيمة، لضمان إتمام معاملات العقارات بسلاسة ونجاح من البداية إلى النهاية." },
        { id: 2, name: 'Real Estate Buying & Selling Brokerage', nameAr: 'الوساطة في بيع العقارات وشرائها', image: 'assets/images/properties/img2.webp', description: "We connect buyers and sellers through trusted, expert-led brokerage services. Our team provides market insights, personalized guidance, and seamless transaction support. We help buyers find the right properties and assist sellers in achieving optimal returns. With professionalism and transparency, we ensure smooth, successful deals across the UAE.", descriptionAr: "نربط المشترين والبائعين من خلال خدمات وساطة موثوقة بقيادة خبراء. يقدم فريقنا رؤىً شاملة للسوق، وإرشادات شخصية، ودعمًا سلسًا للمعاملات. نساعد المشترين في العثور على العقارات المناسبة، ونساعد البائعين على تحقيق أفضل العوائد. باحترافية وشفافية، نضمن صفقات سلسة وناجحة في جميع أنحاء الإمارات العربية المتحدة." },
        { id: 3, name: 'Leasing Property Brokerage Agents', nameAr: 'الوساطة في تأجير العقارات', image: 'assets/images/properties/img3.webp', description: "We offer comprehensive leasing solutions designed to maximize exposure and minimize vacancy periods. Through strategic marketing, targeted outreach, and a deep understanding of local market dynamics, we help landlords lease their properties swiftly, securely, and at the best possible terms.", descriptionAr: "نقدم حلول تأجير شاملة مصممة لتعزيز حضورنا وتقليل فترات الشواغر. من خلال التسويق الاستراتيجي، والتواصل المُستهدف، والفهم العميق لديناميكيات السوق المحلية، نساعد مُلّاك العقارات على تأجير عقاراتهم بسرعة وأمان وبأفضل الشروط الممكنة." },
      ]
    },
    {
      companyId: 3,
      caption: "Technology Solutions Tailored for Your Growth",
      captionAr: 'حلول تكنولوجية مصممة خصيصًا لنموك',
      title: 'UAE Technical Solutions',
      titleAr: 'يو إيه إي للحلول التقنية',
      activities: [
        { id: 1, name: 'Computer Systems Housing Services', nameAr: "خدمات ايواء اجهزة ونظم المعلومات", image: 'assets/images/it/img1.webp', description: "We provide secure and reliable hosting solutions for your computer systems and servers, featuring advanced facilities with environmental controls and power redundancy. Our 24/7 monitoring and expert support ensure maximum uptime and data protection, allowing your business to run smoothly without infrastructure worries.", descriptionAr: "نقدّم حلول استضافة آمنة وموثوقة لأنظمة الحواسيب والخوادم الخاصة بك، مع مرافق متقدمة تشمل ضوابط بيئية ونظام طاقة احتياطي. يضمن فريقنا المتخصص والمراقبة على مدار الساعة أقصى وقت تشغيل وحماية للبيانات، مما يضمن سير أعمالك بسلاسة دون أي قلق بشأن البنية التحتية." },
        { id: 2, name: 'Information Technology Network Services', nameAr: "خدمات شبكات تقنية المعلومات", image: 'assets/images/it/img2.webp', description: "We deliver comprehensive network solutions designed to keep your business connected and secure. Our services include network design, implementation, monitoring, and maintenance, ensuring optimal performance and reliability. With robust security measures and expert support, we help protect your data and enable seamless communication across your organization.", descriptionAr: "نقدم حلولاً شبكية شاملة مصممة للحفاظ على اتصال أعمالك وأمانها. تشمل خدماتنا تصميم الشبكات وتنفيذها ومراقبتها وصيانتها، مما يضمن الأداء الأمثل والموثوقية. بفضل إجراءات الأمان القوية والدعم الفني المتميز، نساعد في حماية بياناتك وتمكين التواصل السلس في مؤسستك." },
        { id: 3, name: 'Data Entry Services', nameAr: "خدمات ادخال البيانات", image: 'assets/images/it/img3.webp', description: "We offer accurate and efficient data entry solutions to help manage and organize your information. Our skilled team ensures fast processing with attention to detail, maintaining data integrity and confidentiality. By streamlining your data management, we support better decision-making and operational efficiency.", descriptionAr: "نقدم حلولاً دقيقة وفعّالة لإدخال البيانات لمساعدتك في إدارة معلوماتك وتنظيمها. يضمن فريقنا الماهر معالجة سريعة مع الاهتمام بالتفاصيل، والحفاظ على سلامة البيانات وسريتها. من خلال تبسيط إدارة بياناتك، ندعم اتخاذ قرارات أفضل وكفاءة تشغيلية." },
        { id: 4, name: 'Internet Content Provider', nameAr: "امداد مواقع الشبكة المعلوماتية (الأنترنت) بالمحتويات", image: 'assets/images/it/img4.webp', description: "We deliver high-quality, relevant digital content tailored to engage your target audience. Our services include content creation, management, and distribution across multiple online platforms. By providing timely and compelling information, we help enhance your brand presence and drive customer interaction.", descriptionAr: "نقدم محتوى رقميًا عالي الجودة وذا صلة، مصمم خصيصًا لجذب جمهورك المستهدف. تشمل خدماتنا إنشاء المحتوى وإدارته وتوزيعه عبر منصات إلكترونية متعددة. من خلال توفير معلومات دقيقة وفعّالة في الوقت المناسب، نساعد في تعزيز حضور علامتك التجارية وزيادة تفاعل العملاء." },
        { id: 5, name: 'IT Infrastructure', nameAr: "انشاء البنية التحتية لتقنية المعلومات", image: 'assets/images/it/img5.webp', description: "We design, build, and maintain robust IT infrastructure that supports your business operations. Our solutions ensure reliable connectivity, secure data storage, and scalable systems to meet your evolving needs. With expert management and proactive support, we help maximize performance and efficiency.", descriptionAr: "نقوم بتصميم وبناء وصيانة بنية تحتية قوية لتكنولوجيا المعلومات تدعم أنشطتكم. تضمن حلولنا اتصالاً موثوقًا، وتخزينًا آمنًا للبيانات، وأنظمة قابلة للتطوير لتلبية احتياجاتكم المتغيرة. بفضل الإدارة الخبيرة والدعم الاستباقي، نساعدكم على تحقيق أقصى قدر من الأداء والكفاءة." },
      ]
    }
  ]

  getCompanyDetails(id: string): CompanyDetails {
    const numericId = Number(id);
    const result = this.companiesDetails.find(companyDetails => companyDetails.companyId === numericId);
    if (!result) {
      throw new Error(`Company with ID ${numericId} not found`);
    }
    return result;
  }
}
